name: Read File in GitHub Actions
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'


jobs:
  starter:
    name: Fetch And Update
    runs-on: ubuntu-latest
    steps:
      - run: pip3 install tqdm
      - uses: actions/checkout@v3
      - run: |
          python3 request.py
          python3 handler.py
          content=$(cat version.txt)
          rm *.apk
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Version $content"
          git push