name: Read File in GitHub Actions
on: [push]


jobs:
  starter:
    name: Fetch And Update
    runs-on: ubuntu-latest
    steps:
      - run: pip3 install tqdm
      - uses: actions/checkout@v3
      - run: |
          python3 __init__.py
          rm *.apk
          content=$(cat version.txt)
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Version $content"
          git push