name: Read File in GitHub Actions
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *'


jobs:
  starter:
    name: Request url and handle data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          python3 request.py
      - run: pip3 install tqdm
      - run: |
          python3 downloader.py
          python3 handler.py
          rm *.apk
          rm temp.txt
      - run: |
          content=$(cat version.txt)
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Version $content"
          git push
