name: Handle it without Lowiro API
on:
  workflow_dispatch:
    inputs:
      url:
        description: "download url"
        required: true
        type: string
      version:
        description: "version"
        required: true
        type: string
permissions: write-all


jobs:
  starter:
    name: Fetch And Update
    runs-on: ubuntu-latest
    steps:
      - run: pip3 install tqdm
      - uses: actions/checkout@v3
      - run: |
          python3 request.py ${{ inputs.url }} ${{ inputs.version}}
      - run: |
          python3 handler.py
          content=$(cat version.txt)
          rm *.apk
      - run: |
          content=$(cat version.txt)
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Version $content"
          git push
