name: Handle it without Lowiro API
on:
  workflow_dispatch:
    inputs:
      url:
        description: "download url"
        required: true
        type: string
      version:
        description: "version"
        required: true
        type: string
permissions: write-all


jobs:
  starter:
    name: Fetch And Update
    runs-on: ubuntu-latest
    steps:
      - run: curl -O ${{ github.event.inputs.url }} 
      - uses: actions/checkout@v3
      - run:
          find / -name "arcaea_4.6.0c.apk"
          content=${{ github.event.inputs.version }}
          echo $content > version.txt
      - run:
            python3 handler.py
            rm *.apk 
      - run:
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Version $content"
          git push